name: Docker CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t kaizenacademy/kaizen:1.0 .

      - name: Docker tag
        run: docker tag kaizenacademy/kaizen:1.0 kaizenacademy/kaizen:1.0.0
