name: Docker CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t karabalta75/kaizen:1.0 .

      - name: Docker tag
        run: docker tag karabalta75/kaizen:1.0 karabalta75/kaizen:1.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push image to Docker Hub
        run: docker push karabalta75/kaizen:1.0.0
